[package]
name = "sapho-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Sapho runtime module."

[lints]
workspace = true

[dependencies]
sapho-core.workspace = true
sapho-graph.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
futures.workspace = true

[dev-dependencies]
tokio.workspace = true
async-trait.workspace = true
