[package]
name = "sapho-graph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Sapho graph module."

[lints]
workspace = true

[dependencies]
sapho-core.workspace = true
serde.workspace = true
serde-saphyr.workspace = true
serde_stacker.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
async-trait.workspace = true
